Read db passwords from env file
departement-loire-atlantique/publik pull request #4
Opened 2020-01-07 10:18 UTC by Vayel

2020-01-20 11:45 UTC, Vayel commented
@lbarro how can this PR benefite to this repo?

2020-01-21 17:49 UTC, Vayel commented
@lbarro @julien-bayle @julienbayle @GuillaumeGautierLA I can split this into multiple PRs.

2020-01-23 14:03 UTC, julien-bayle commented
This is a good idea. 
My collegue @labarro will merge it soon as I'm going to be out of office for a few months.

Thx for this PR.

2020-01-23 14:04 UTC, julien-bayle approved these changes

2020-01-23 14:06 UTC, julien-bayle approved these changes

2020-01-23 14:07 UTC, julien-bayle submitted a review, later dismissed

2020-01-23 14:44 UTC, Vayel commented
I had some problems making it work so I asked Entrouvert and, apparently, Publik wasn't designed to work on multiple containers. All components need to be installed on the same machine (or container).

I'm trying to merge the containers while keeping the automation and the configuration with Docker and env vars.

2020-01-23 15:07 UTC, julien-bayle requested changes

2020-01-23 15:07 UTC, julien-bayle commented on .gitignore
> +data/*
Adding a star is useless

2020-01-23 15:07 UTC, julien-bayle commented on base/pyenv.template
> +MAILCATCHER_SMTP_PORT = '$MAILCATCHER_SMTP_PORT'
Let's rename it SMTP_PORT

2020-01-23 15:07 UTC, julien-bayle commented on check-install.sh
> +echo "Installation OK"
Use wc -l to check that directory is not empty as the message always say "OK" even if installation is not OK

2020-01-23 15:07 UTC, julien-bayle commented on combo/Dockerfile
> +RUN rm -rf /var/lib/apt/lists/*
If you split this RUN in multiple line then the image size will be larger. There is no point in splitting it

2020-01-23 15:07 UTC, julien-bayle commented on wcs/wcs.settings.py
> +            'level': 'DEBUG',
Perhaps we should add a variable for this.

2020-01-23 15:07 UTC, julien-bayle commented on passerelle/passerelle.settings.py
> +            'level': 'DEBUG',
Perhaps we should add a variable for this.

2020-01-23 15:07 UTC, julien-bayle commented on hobo/hobo.settings.py
> +            'level': 'DEBUG',
Perhaps we should add a variable for this.

2020-01-23 15:07 UTC, julien-bayle commented on fargo/fargo.settings.py
> +            'level': 'DEBUG',
Perhaps we should add a variable for this.

2020-01-23 15:07 UTC, julien-bayle commented on install-on-debian.sh
> -echo "Add publik.bash to bash env of publik user..."
Why do you remove these aliases ?

2020-01-23 15:07 UTC, julien-bayle commented on proxy/docker-entrypoint.sh
> -generateconf demarches combo http
Should use the subdomains variable

2020-01-23 15:07 UTC, julien-bayle commented on docs/deploy-prod.md
> +TODO
Exclude this commit from PR as the doc is not ready yet

2020-01-23 15:07 UTC, julien-bayle commented on docs/deploy-local.md
> +TODO
Exclude this commit from PR as the doc is not ready yet

2020-01-23 15:07 UTC, julien-bayle commented on docs/deploy-dev.md
> +```
Exclude this commit from PR as the doc is not ready yet

2020-01-23 15:07 UTC, julien-bayle commented on authentic/authentic.config.py
> +            'level': 'DEBUG',
Should use a variable like LOGGER_LEVEL

2020-01-23 15:07 UTC, julien-bayle commented on authentic/authentic.config.py
> +            'filename': '/var/log/authentic2-multitenant/django.log',
Logs are available in systemd... adding a file log in production must be an option as a log rotate mecanism should also be configured (already available in systemd)

2020-01-23 15:07 UTC, julien-bayle commented on combo/combo.settings.py
> +            'level': 'DEBUG',
File logging and log level should be in a variable

2020-01-23 15:07 UTC, julien-bayle commented on docs/README.md
> +* `docs/deploy-prod.md` pour une installation de production sur une machine **accessible** depuis Internet
Good "new" documentation. 
Anyway, can you move it in another PR as could be merged separately ?

2020-01-23 15:30 UTC, Vayel commented
@julien-bayle we can have a call if you want (I sent you my phone number on LinkedIn).

2020-01-23 15:36 UTC, Vayel commented on combo/Dockerfile
> +RUN rm -rf /var/lib/apt/lists/*
Ok. Can you explain what `rm -rf /var/lib/apt/lists/*` is for?

2020-01-23 15:39 UTC, Vayel commented on install-on-debian.sh
> -echo "Add publik.bash to bash env of publik user..."
I find it cleaner to avoid "polluting" the user's environment outside the project.

2020-01-31 09:33 UTC, julien-bayle commented on combo/Dockerfile
> +RUN rm -rf /var/lib/apt/lists/*
This line removes apt cache files in the current image layer making it smaller (See best pratice https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run)

2020-01-31 09:49 UTC, julien-bayle commented on install-on-debian.sh
> -echo "Add publik.bash to bash env of publik user..."
Why not. However the main documentation refers to all these aliases... so removing it also breaks all the documentation (README.md). I propose to keep it for now and create a PR later that will add .sh script for all aliases, update main doc and remove the bash aliases file.

2020-01-31 14:19 UTC, julien-bayle commented on authentic/authentic.config.py
> +            'filename': '/var/log/authentic2-multitenant/django.log',
I just pushed in this branch an initial implementation for this

2020-01-31 14:20 UTC, julien-bayle commented on install-on-debian.sh
> -echo "Add publik.bash to bash env of publik user..."
I restored this part to merge this PR

2020-01-31 14:21 UTC, julien-bayle approved these changes

2020-01-31 14:23 UTC, merged

2020-01-31 14:23 UTC, julien-bayle commented
Thx !